import type { Metadata } from "next";
import {Work_Sans, Trirong } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer/Footer";


const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  
})


const trirong = Trirong({
  variable: "--font-trirong",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Website RDK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${trirong.variable}  antialiased`}>
        
        <Navbar/>
        {children}


        <Footer/> 
      

      </body>
    </html>
  );
}
