import type { Metadata } from "next";
import { Work_Sans, Trirong } from "next/font/google";
import "./globals.css";

const trirong = Trirong({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-trirong",
});

const worksans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-worksans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${worksans.variable} ${trirong.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
